<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="Notifications.Wpf" Version="0.1.1" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit.Analyzers" Version="4.4.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\ViewModels\MainViewModel.cs" Link="MainViewModel.cs" />
    <Compile Include="..\ViewModels\RelayCommand.cs" Link="RelayCommand.cs" />
    <Compile Include="..\ViewModels\ViewModelBase.cs" Link="ViewModelBase.cs" />
    <Compile Include="..\Models\ClipboardItem.cs" Link="ClipboardItem.cs" />
    <Compile Include="..\Models\Settings.cs" Link="Settings.cs" />
    <Compile Include="..\Services\IClipboardService.cs" Link="IClipboardService.cs" />
    <Compile Include="..\Services\INotificationService.cs" Link="INotificationService.cs" />
  </ItemGroup>

</Project>
